"""Initial migration

Revision ID: 4c40155b6cef
Revises: 
Create Date: 2023-10-30 09:23:38.041721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c40155b6cef'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicle_metadata',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('vehicle_type', sa.String(length=50), nullable=False),
    sa.Column('manufacturer', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_type')
    )
    op.create_table('vehicle_info',
    sa.Column('vehicle_number', sa.String(length=50), nullable=False),
    sa.Column('vehicle_type_id', sa.Integer(), nullable=False),
    sa.Column('model_year', sa.Integer(), nullable=False),
    sa.Column('fuel_type', sa.String(length=50), nullable=False),
    sa.Column('terminal_info', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_type_id'], ['vehicle_metadata.id'], ),
    sa.PrimaryKeyConstraint('vehicle_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehicle_info')
    op.drop_table('vehicle_metadata')
    # ### end Alembic commands ###
