"""change VehicleInfo.model_year -> VehicleInfo.year

Revision ID: 9816c75f7152
Revises: 4c40155b6cef
Create Date: 2023-10-30 13:06:57.272843

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '9816c75f7152'
down_revision: Union[str, None] = '4c40155b6cef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_info', sa.Column('year', sa.Integer(), nullable=False))
    op.drop_column('vehicle_info', 'model_year')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicle_info', sa.Column('model_year', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('vehicle_info', 'year')
    # ### end Alembic commands ###
